// Code generated by entc, DO NOT EDIT.

package helditems

const (
	// Label holds the string label denoting the helditems type in the database.
	Label = "held_items"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPhysicalMovePowerCorrectionValue holds the string denoting the physical_move_power_correction_value field in the database.
	FieldPhysicalMovePowerCorrectionValue = "physical_move_power_correction_value"
	// FieldSpecialMovePowerCorrectionValue holds the string denoting the special_move_power_correction_value field in the database.
	FieldSpecialMovePowerCorrectionValue = "special_move_power_correction_value"
	// FieldAttackPowerCorrectionValue holds the string denoting the attack_power_correction_value field in the database.
	FieldAttackPowerCorrectionValue = "attack_power_correction_value"
	// FieldSpecialAttackPowerCorrectionValue holds the string denoting the special_attack_power_correction_value field in the database.
	FieldSpecialAttackPowerCorrectionValue = "special_attack_power_correction_value"
	// FieldAttackCorrectionValue holds the string denoting the attack_correction_value field in the database.
	FieldAttackCorrectionValue = "attack_correction_value"
	// FieldSpecialAttackCorrectionValue holds the string denoting the special_attack_correction_value field in the database.
	FieldSpecialAttackCorrectionValue = "special_attack_correction_value"
	// FieldDeffenseCorrectionValue holds the string denoting the deffense_correction_value field in the database.
	FieldDeffenseCorrectionValue = "deffense_correction_value"
	// FieldSpecialDeffenseCorrectionValue holds the string denoting the special_deffense_correction_value field in the database.
	FieldSpecialDeffenseCorrectionValue = "special_deffense_correction_value"
	// FieldDamageCorrectionType1 holds the string denoting the damage_correction_type1 field in the database.
	FieldDamageCorrectionType1 = "damage_correction_type1"
	// FieldDamageCorrectionValue1 holds the string denoting the damage_correction_value1 field in the database.
	FieldDamageCorrectionValue1 = "damage_correction_value1"
	// FieldDamageCorrectionType2 holds the string denoting the damage_correction_type2 field in the database.
	FieldDamageCorrectionType2 = "damage_correction_type2"
	// FieldDamageCorrectionValue2 holds the string denoting the damage_correction_value2 field in the database.
	FieldDamageCorrectionValue2 = "damage_correction_value2"
	// FieldWeightCorrectionValue holds the string denoting the weight_correction_value field in the database.
	FieldWeightCorrectionValue = "weight_correction_value"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeToTrainedPokemonItem holds the string denoting the to_trained_pokemon_item edge name in mutations.
	EdgeToTrainedPokemonItem = "to_trained_pokemon_item"
	// Table holds the table name of the helditems in the database.
	Table = "held_items"
	// ToTrainedPokemonItemTable is the table that holds the to_trained_pokemon_item relation/edge.
	ToTrainedPokemonItemTable = "trained_pokemon_details"
	// ToTrainedPokemonItemInverseTable is the table name for the TrainedPokemonDetails entity.
	// It exists in this package in order to avoid circular dependency with the "trainedpokemondetails" package.
	ToTrainedPokemonItemInverseTable = "trained_pokemon_details"
	// ToTrainedPokemonItemColumn is the table column denoting the to_trained_pokemon_item relation/edge.
	ToTrainedPokemonItemColumn = "held_item_id"
)

// Columns holds all SQL columns for helditems fields.
var Columns = []string{
	FieldID,
	FieldPhysicalMovePowerCorrectionValue,
	FieldSpecialMovePowerCorrectionValue,
	FieldAttackPowerCorrectionValue,
	FieldSpecialAttackPowerCorrectionValue,
	FieldAttackCorrectionValue,
	FieldSpecialAttackCorrectionValue,
	FieldDeffenseCorrectionValue,
	FieldSpecialDeffenseCorrectionValue,
	FieldDamageCorrectionType1,
	FieldDamageCorrectionValue1,
	FieldDamageCorrectionType2,
	FieldDamageCorrectionValue2,
	FieldWeightCorrectionValue,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPhysicalMovePowerCorrectionValue holds the default value on creation for the "physical_move_power_correction_value" field.
	DefaultPhysicalMovePowerCorrectionValue int
	// DefaultSpecialMovePowerCorrectionValue holds the default value on creation for the "special_move_power_correction_value" field.
	DefaultSpecialMovePowerCorrectionValue int
	// DefaultAttackPowerCorrectionValue holds the default value on creation for the "attack_power_correction_value" field.
	DefaultAttackPowerCorrectionValue int
	// DefaultSpecialAttackPowerCorrectionValue holds the default value on creation for the "special_attack_power_correction_value" field.
	DefaultSpecialAttackPowerCorrectionValue int
	// DefaultAttackCorrectionValue holds the default value on creation for the "attack_correction_value" field.
	DefaultAttackCorrectionValue int
	// DefaultSpecialAttackCorrectionValue holds the default value on creation for the "special_attack_correction_value" field.
	DefaultSpecialAttackCorrectionValue int
	// DefaultDeffenseCorrectionValue holds the default value on creation for the "deffense_correction_value" field.
	DefaultDeffenseCorrectionValue int
	// DefaultSpecialDeffenseCorrectionValue holds the default value on creation for the "special_deffense_correction_value" field.
	DefaultSpecialDeffenseCorrectionValue int
	// DamageCorrectionType1Validator is a validator for the "damage_correction_type1" field. It is called by the builders before save.
	DamageCorrectionType1Validator func(string) error
	// DefaultDamageCorrectionValue1 holds the default value on creation for the "damage_correction_value1" field.
	DefaultDamageCorrectionValue1 int
	// DefaultWeightCorrectionValue holds the default value on creation for the "weight_correction_value" field.
	DefaultWeightCorrectionValue int
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
