package types

import "github.com/Symthy/PokeRest/pokeRest/domain/value"

type typeTable = map[value.PokemonType]map[value.PokemonType]float32

type TypeCompatibilityTable struct {
	compatibilityTable typeTable
	typeOrder          PokemonTypes
}

func NewTypeCompatibilityTable() TypeCompatibilityTable {
	return TypeCompatibilityTable{
		compatibilityTable: buildCompatibilityTable(),
		typeOrder:          NewPokemonTypes(),
	}
}

func (t TypeCompatibilityTable) GenerateTypeDamageRateTable() [][]float32 {
	typeTable := [][]float32{}
	for _, attackType := range t.typeOrder.Items() {
		typeRecord := make([]float32, t.typeOrder.Size())
		for j, blockType := range t.typeOrder.Items() {
			typeRecord[j] = t.compatibilityTable[attackType][blockType]
		}
		typeTable = append(typeTable, typeRecord)
	}
	return typeTable
}

func (t TypeCompatibilityTable) GenerateTypeNames(lang string) []string {
	return t.typeOrder.GenerateTypeNames(lang)
}

func (t TypeCompatibilityTable) ResolveAttackTypeCompatibility(attackType value.PokemonType) TypeCompatibility {
	var typeToDamageRate map[value.PokemonType]float32 = t.compatibilityTable[attackType]
	return NewTypeCompatibility(attackType, typeToDamageRate, t.typeOrder)
}

func (t TypeCompatibilityTable) ResolveDeffenceTypeCompatibility(deffenceType value.PokemonType) TypeCompatibility {
	deffenceTypeToDamageRate := map[value.PokemonType]float32{}
	for pType, pTypeToDamageRate := range t.compatibilityTable {
		deffenceTypeToDamageRate[pType] = pTypeToDamageRate[deffenceType]
	}
	return NewTypeCompatibility(deffenceType, deffenceTypeToDamageRate, t.typeOrder)
}

func buildCompatibilityTable() typeTable {
	table := map[value.PokemonType]map[value.PokemonType]float32{
		value.Normal(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     0.5,
			value.Ghost():    0,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Fire(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    0.5,
			value.Electric(): 1,
			value.Grass():    2,
			value.Ice():      2,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      2,
			value.Rock():     0.5,
			value.Ghost():    1,
			value.Dragon():   0.5,
			value.Dark():     1,
			value.Steel():    2,
			value.Fairy():    1,
		},
		value.Water(): {
			value.Normal():   1,
			value.Fire():     2,
			value.Water():    0.5,
			value.Electric(): 1,
			value.Grass():    0.5,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   2,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     2,
			value.Ghost():    1,
			value.Dragon():   0.5,
			value.Dark():     1,
			value.Steel():    1,
			value.Fairy():    1,
		},
		value.Electric(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    2,
			value.Electric(): 0.5,
			value.Grass():    0.5,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   0,
			value.Flying():   2,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   0.5,
			value.Dark():     1,
			value.Steel():    1,
			value.Fairy():    1,
		},
		value.Grass(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    2,
			value.Electric(): 1,
			value.Grass():    0.5,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   0.5,
			value.Ground():   2,
			value.Flying():   0.5,
			value.Psychic():  1,
			value.Bug():      0.5,
			value.Rock():     2,
			value.Ghost():    1,
			value.Dragon():   0.5,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Ice(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    0.5,
			value.Electric(): 1,
			value.Grass():    2,
			value.Ice():      0.5,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   2,
			value.Flying():   2,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   2,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Fighting(): {
			value.Normal():   2,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      2,
			value.Fighting(): 1,
			value.Poison():   0.5,
			value.Ground():   1,
			value.Flying():   0.5,
			value.Psychic():  0.5,
			value.Bug():      0.5,
			value.Rock():     2,
			value.Ghost():    0,
			value.Dragon():   1,
			value.Dark():     2,
			value.Steel():    2,
			value.Fairy():    0.5,
		},
		value.Poison(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    2,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   0.5,
			value.Ground():   0.5,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     0.5,
			value.Ghost():    0.5,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    0,
			value.Fairy():    2,
		},
		value.Ground(): {
			value.Normal():   1,
			value.Fire():     2,
			value.Water():    1,
			value.Electric(): 2,
			value.Grass():    0.5,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   2,
			value.Ground():   1,
			value.Flying():   0,
			value.Psychic():  1,
			value.Bug():      0.5,
			value.Rock():     2,
			value.Ghost():    1,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    2,
			value.Fairy():    1,
		},
		value.Flying(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 0.5,
			value.Grass():    2,
			value.Ice():      1,
			value.Fighting(): 2,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      2,
			value.Rock():     0.5,
			value.Ghost():    1,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Psychic(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 2,
			value.Poison():   2,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  0.5,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   1,
			value.Dark():     0,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Bug(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    2,
			value.Ice():      1,
			value.Fighting(): 0.5,
			value.Poison():   0.5,
			value.Ground():   1,
			value.Flying():   0.5,
			value.Psychic():  2,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    0.5,
			value.Dragon():   1,
			value.Dark():     2,
			value.Steel():    0.5,
			value.Fairy():    0.5,
		},
		value.Rock(): {
			value.Normal():   1,
			value.Fire():     2,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      2,
			value.Fighting(): 0.5,
			value.Poison():   1,
			value.Ground():   0.5,
			value.Flying():   2,
			value.Psychic():  1,
			value.Bug():      2,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
		value.Ghost(): {
			value.Normal():   0,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  2,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    2,
			value.Dragon():   1,
			value.Dark():     0.5,
			value.Steel():    1,
			value.Fairy():    1,
		},
		value.Dragon(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   2,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    0,
		},
		value.Dark(): {
			value.Normal():   1,
			value.Fire():     1,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 0.5,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  2,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    2,
			value.Dragon():   1,
			value.Dark():     0.5,
			value.Steel():    1,
			value.Fairy():    0.5,
		},
		value.Steel(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    0.5,
			value.Electric(): 0.5,
			value.Grass():    1,
			value.Ice():      2,
			value.Fighting(): 1,
			value.Poison():   1,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     2,
			value.Ghost():    1,
			value.Dragon():   1,
			value.Dark():     1,
			value.Steel():    0.5,
			value.Fairy():    2,
		},
		value.Fairy(): {
			value.Normal():   1,
			value.Fire():     0.5,
			value.Water():    1,
			value.Electric(): 1,
			value.Grass():    1,
			value.Ice():      1,
			value.Fighting(): 2,
			value.Poison():   0.5,
			value.Ground():   1,
			value.Flying():   1,
			value.Psychic():  1,
			value.Bug():      1,
			value.Rock():     1,
			value.Ghost():    1,
			value.Dragon():   2,
			value.Dark():     2,
			value.Steel():    0.5,
			value.Fairy():    1,
		},
	}
	return table
}
