package types

import "github.com/Symthy/PokeRest/pokeRest/domain/value"

type typeTable = map[value.PokemonType]map[value.PokemonType]float32

type TypeCompatibility struct {
	compatibilityTable typeTable
	types              PokemonTypes
}

func NewTypeCompatibility() TypeCompatibility {
	return TypeCompatibility{
		compatibilityTable: buildCompatibilityTable(),
		types:              NewPokemonTypes(),
	}
}

func (t TypeCompatibility) GenerateTypeCompatibilityTable() [][]float32 {
	typeTable := [][]float32{}
	for _, attackType := range t.types.Items() {
		typeRecord := make([]float32, t.typeNum())
		for j, blockType := range t.types.Items() {
			typeRecord[j] = t.compatibilityTable[attackType][blockType]
		}
		typeTable = append(typeTable, typeRecord)
	}
	return typeTable
}

func (t TypeCompatibility) GenerateTypeNames(lang string) []string {
	return t.types.GenerateTypeNames(lang)
}

func (t TypeCompatibility) typeNum() int {
	return t.types.Size()
}

func buildCompatibilityTable() typeTable {
	table := map[value.PokemonType]map[value.PokemonType]float32{
		value.PokemonTypeNormal: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     0.5,
			value.PokemonTypeGhost:    0,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeFire: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    0.5,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    2,
			value.PokemonTypeIce:      2,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      2,
			value.PokemonTypeRock:     0.5,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   0.5,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    2,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeWater: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     2,
			value.PokemonTypeWater:    0.5,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    0.5,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   2,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     2,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   0.5,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    1,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeElectric: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    2,
			value.PokemonTypeElectric: 0.5,
			value.PokemonTypeGrass:    0.5,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   0,
			value.PokemonTypeFlying:   2,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   0.5,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    1,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeGrass: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    2,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    0.5,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   0.5,
			value.PokemonTypeGround:   2,
			value.PokemonTypeFlying:   0.5,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      0.5,
			value.PokemonTypeRock:     2,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   0.5,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeIce: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    0.5,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    2,
			value.PokemonTypeIce:      0.5,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   2,
			value.PokemonTypeFlying:   2,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   2,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeFighting: {
			value.PokemonTypeNormal:   2,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      2,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   0.5,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   0.5,
			value.PokemonTypePsychic:  0.5,
			value.PokemonTypeBug:      0.5,
			value.PokemonTypeRock:     2,
			value.PokemonTypeGhost:    0,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     2,
			value.PokemonTypeSteel:    2,
			value.PokemonTypeFairy:    0.5,
		},
		value.PokemonTypePoison: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    2,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   0.5,
			value.PokemonTypeGround:   0.5,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     0.5,
			value.PokemonTypeGhost:    0.5,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0,
			value.PokemonTypeFairy:    2,
		},
		value.PokemonTypeGround: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     2,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 2,
			value.PokemonTypeGrass:    0.5,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   2,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   0,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      0.5,
			value.PokemonTypeRock:     2,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    2,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeFlying: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 0.5,
			value.PokemonTypeGrass:    2,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 2,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      2,
			value.PokemonTypeRock:     0.5,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypePsychic: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 2,
			value.PokemonTypePoison:   2,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  0.5,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     0,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeBug: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    2,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 0.5,
			value.PokemonTypePoison:   0.5,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   0.5,
			value.PokemonTypePsychic:  2,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    0.5,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     2,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    0.5,
		},
		value.PokemonTypeRock: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     2,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      2,
			value.PokemonTypeFighting: 0.5,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   0.5,
			value.PokemonTypeFlying:   2,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      2,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeGhost: {
			value.PokemonTypeNormal:   0,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  2,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    2,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     0.5,
			value.PokemonTypeSteel:    1,
			value.PokemonTypeFairy:    1,
		},
		value.PokemonTypeDragon: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   2,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    0,
		},
		value.PokemonTypeDark: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     1,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 0.5,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  2,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    2,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     0.5,
			value.PokemonTypeSteel:    1,
			value.PokemonTypeFairy:    0.5,
		},
		value.PokemonTypeSteel: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    0.5,
			value.PokemonTypeElectric: 0.5,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      2,
			value.PokemonTypeFighting: 1,
			value.PokemonTypePoison:   1,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     2,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   1,
			value.PokemonTypeDark:     1,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    2,
		},
		value.PokemonTypeFairy: {
			value.PokemonTypeNormal:   1,
			value.PokemonTypeFire:     0.5,
			value.PokemonTypeWater:    1,
			value.PokemonTypeElectric: 1,
			value.PokemonTypeGrass:    1,
			value.PokemonTypeIce:      1,
			value.PokemonTypeFighting: 2,
			value.PokemonTypePoison:   0.5,
			value.PokemonTypeGround:   1,
			value.PokemonTypeFlying:   1,
			value.PokemonTypePsychic:  1,
			value.PokemonTypeBug:      1,
			value.PokemonTypeRock:     1,
			value.PokemonTypeGhost:    1,
			value.PokemonTypeDragon:   2,
			value.PokemonTypeDark:     2,
			value.PokemonTypeSteel:    0.5,
			value.PokemonTypeFairy:    1,
		},
	}
	return table
}
