/*
 * PokeRest
 *
 * PokeRest API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Move struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Type string `json:"type"`

	// 分類（物理/特殊）
	Species string `json:"species,omitempty"`

	// 威力
	Power float32 `json:"power"`

	// 威力（ダイマックス技等）
	SpecialMovePower float32 `json:"specialMovePower"`

	// 命中
	Accuracy float32 `json:"accuracy"`

	// PP
	Pp float32 `json:"pp"`

	// 接触/非接触
	IsContactMove bool `json:"isContactMove"`

	// 守る
	IsCanGuard bool `json:"isCanGuard"`
}
