/*
 * PokeRest
 *
 * PokeRest API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PokemonAvilities - 指定ポケモンの特性一覧
type PokemonAvilities struct {

	Id string `json:"id"`

	Avilities []Ability `json:"avilities"`
}
