// Code generated by entc, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent"
)

// The AbilitiesFunc type is an adapter to allow the use of ordinary
// function as Abilities mutator.
type AbilitiesFunc func(context.Context, *ent.AbilitiesMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AbilitiesFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.AbilitiesMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AbilitiesMutation", m)
	}
	return f(ctx, mv)
}

// The BattleOpponentPartyFunc type is an adapter to allow the use of ordinary
// function as BattleOpponentParty mutator.
type BattleOpponentPartyFunc func(context.Context, *ent.BattleOpponentPartyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BattleOpponentPartyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.BattleOpponentPartyMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BattleOpponentPartyMutation", m)
	}
	return f(ctx, mv)
}

// The BattleRecordsFunc type is an adapter to allow the use of ordinary
// function as BattleRecords mutator.
type BattleRecordsFunc func(context.Context, *ent.BattleRecordsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BattleRecordsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.BattleRecordsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BattleRecordsMutation", m)
	}
	return f(ctx, mv)
}

// The FormsFunc type is an adapter to allow the use of ordinary
// function as Forms mutator.
type FormsFunc func(context.Context, *ent.FormsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FormsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.FormsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FormsMutation", m)
	}
	return f(ctx, mv)
}

// The HeldItemsFunc type is an adapter to allow the use of ordinary
// function as HeldItems mutator.
type HeldItemsFunc func(context.Context, *ent.HeldItemsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f HeldItemsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.HeldItemsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.HeldItemsMutation", m)
	}
	return f(ctx, mv)
}

// The MovesFunc type is an adapter to allow the use of ordinary
// function as Moves mutator.
type MovesFunc func(context.Context, *ent.MovesMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MovesFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.MovesMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MovesMutation", m)
	}
	return f(ctx, mv)
}

// The PartyFunc type is an adapter to allow the use of ordinary
// function as Party mutator.
type PartyFunc func(context.Context, *ent.PartyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PartyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.PartyMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PartyMutation", m)
	}
	return f(ctx, mv)
}

// The PartyResultRecordFunc type is an adapter to allow the use of ordinary
// function as PartyResultRecord mutator.
type PartyResultRecordFunc func(context.Context, *ent.PartyResultRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PartyResultRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.PartyResultRecordMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PartyResultRecordMutation", m)
	}
	return f(ctx, mv)
}

// The PokemonsFunc type is an adapter to allow the use of ordinary
// function as Pokemons mutator.
type PokemonsFunc func(context.Context, *ent.PokemonsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PokemonsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.PokemonsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PokemonsMutation", m)
	}
	return f(ctx, mv)
}

// The TagsFunc type is an adapter to allow the use of ordinary
// function as Tags mutator.
type TagsFunc func(context.Context, *ent.TagsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TagsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TagsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TagsMutation", m)
	}
	return f(ctx, mv)
}

// The TrainedPokemonDetailsFunc type is an adapter to allow the use of ordinary
// function as TrainedPokemonDetails mutator.
type TrainedPokemonDetailsFunc func(context.Context, *ent.TrainedPokemonDetailsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TrainedPokemonDetailsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TrainedPokemonDetailsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TrainedPokemonDetailsMutation", m)
	}
	return f(ctx, mv)
}

// The TrainedPokemonsFunc type is an adapter to allow the use of ordinary
// function as TrainedPokemons mutator.
type TrainedPokemonsFunc func(context.Context, *ent.TrainedPokemonsMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TrainedPokemonsFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TrainedPokemonsMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TrainedPokemonsMutation", m)
	}
	return f(ctx, mv)
}

// The TypeCompatibilityFunc type is an adapter to allow the use of ordinary
// function as TypeCompatibility mutator.
type TypeCompatibilityFunc func(context.Context, *ent.TypeCompatibilityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TypeCompatibilityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.TypeCompatibilityMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TypeCompatibilityMutation", m)
	}
	return f(ctx, mv)
}

// The UsersFunc type is an adapter to allow the use of ordinary
// function as Users mutator.
type UsersFunc func(context.Context, *ent.UsersMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UsersFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.UsersMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UsersMutation", m)
	}
	return f(ctx, mv)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
//
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
//
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
//
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
//
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
