// Code generated by entc, DO NOT EDIT.

package users

const (
	// Label holds the string label denoting the users type in the database.
	Label = "users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// EdgeUserTrainedPokemon holds the string denoting the user_trained_pokemon edge name in mutations.
	EdgeUserTrainedPokemon = "user_trained_pokemon"
	// EdgeUserTrainedPokemonDetail holds the string denoting the user_trained_pokemon_detail edge name in mutations.
	EdgeUserTrainedPokemonDetail = "user_trained_pokemon_detail"
	// Table holds the table name of the users in the database.
	Table = "users"
	// UserTrainedPokemonTable is the table that holds the user_trained_pokemon relation/edge.
	UserTrainedPokemonTable = "trained_pokemons"
	// UserTrainedPokemonInverseTable is the table name for the TrainedPokemons entity.
	// It exists in this package in order to avoid circular dependency with the "trainedpokemons" package.
	UserTrainedPokemonInverseTable = "trained_pokemons"
	// UserTrainedPokemonColumn is the table column denoting the user_trained_pokemon relation/edge.
	UserTrainedPokemonColumn = "create_user_id"
	// UserTrainedPokemonDetailTable is the table that holds the user_trained_pokemon_detail relation/edge.
	UserTrainedPokemonDetailTable = "trained_pokemon_details"
	// UserTrainedPokemonDetailInverseTable is the table name for the TrainedPokemonDetails entity.
	// It exists in this package in order to avoid circular dependency with the "trainedpokemondetails" package.
	UserTrainedPokemonDetailInverseTable = "trained_pokemon_details"
	// UserTrainedPokemonDetailColumn is the table column denoting the user_trained_pokemon_detail relation/edge.
	UserTrainedPokemonDetailColumn = "user_id"
)

// Columns holds all SQL columns for users fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDisplayName,
	FieldEmail,
	FieldRole,
	FieldProfile,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
)
