/*
 * PokeRest
 *
 * PokeRest API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetAbilities - GET Abilities
func GetAbilities(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAbilitiesId - GET Ability
func GetAbilitiesId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetMoves - Your GET endpoint
func GetMoves(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetMovesId - GET Move
func GetMovesId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPokemonAvilities - GET Avilities of Specify Pokemon
func GetPokemonAvilities(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPokemonMovesPokemonId - GET Moves of Specify Pokemon
func GetPokemonMovesPokemonId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPokemons - GET Pokemons
func GetPokemons(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPokemonsId - GET Pokemon
func GetPokemonsId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTypeCompabilityDefenseType - GET Type Compability Defense Side
func GetTypeCompabilityDefenseType(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTypeCompabilityType - GET Type Compability Attack Side
func GetTypeCompabilityType(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTypes - Your GET Types
func GetTypes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetTypesCompability - GET Type Compability
func GetTypesCompability(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
