/*
 * PokeRest
 *
 * PokeRest API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Ability struct {

	Id float32 `json:"id"`

	Name string `json:"name"`

	Effect string `json:"effect"`
}
