// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/battleopponentparty"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/battlerecords"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/party"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/predicate"
)

// BattleRecordsQuery is the builder for querying BattleRecords entities.
type BattleRecordsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.BattleRecords
	// eager-loading edges.
	withUseParty      *PartyQuery
	withOpponentParty *BattleOpponentPartyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BattleRecordsQuery builder.
func (brq *BattleRecordsQuery) Where(ps ...predicate.BattleRecords) *BattleRecordsQuery {
	brq.predicates = append(brq.predicates, ps...)
	return brq
}

// Limit adds a limit step to the query.
func (brq *BattleRecordsQuery) Limit(limit int) *BattleRecordsQuery {
	brq.limit = &limit
	return brq
}

// Offset adds an offset step to the query.
func (brq *BattleRecordsQuery) Offset(offset int) *BattleRecordsQuery {
	brq.offset = &offset
	return brq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (brq *BattleRecordsQuery) Unique(unique bool) *BattleRecordsQuery {
	brq.unique = &unique
	return brq
}

// Order adds an order step to the query.
func (brq *BattleRecordsQuery) Order(o ...OrderFunc) *BattleRecordsQuery {
	brq.order = append(brq.order, o...)
	return brq
}

// QueryUseParty chains the current query on the "use_party" edge.
func (brq *BattleRecordsQuery) QueryUseParty() *PartyQuery {
	query := &PartyQuery{config: brq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battlerecords.Table, battlerecords.FieldID, selector),
			sqlgraph.To(party.Table, party.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, battlerecords.UsePartyTable, battlerecords.UsePartyColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOpponentParty chains the current query on the "opponent_party" edge.
func (brq *BattleRecordsQuery) QueryOpponentParty() *BattleOpponentPartyQuery {
	query := &BattleOpponentPartyQuery{config: brq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battlerecords.Table, battlerecords.FieldID, selector),
			sqlgraph.To(battleopponentparty.Table, battleopponentparty.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, battlerecords.OpponentPartyTable, battlerecords.OpponentPartyColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BattleRecords entity from the query.
// Returns a *NotFoundError when no BattleRecords was found.
func (brq *BattleRecordsQuery) First(ctx context.Context) (*BattleRecords, error) {
	nodes, err := brq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{battlerecords.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (brq *BattleRecordsQuery) FirstX(ctx context.Context) *BattleRecords {
	node, err := brq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BattleRecords ID from the query.
// Returns a *NotFoundError when no BattleRecords ID was found.
func (brq *BattleRecordsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = brq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{battlerecords.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (brq *BattleRecordsQuery) FirstIDX(ctx context.Context) int {
	id, err := brq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BattleRecords entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one BattleRecords entity is not found.
// Returns a *NotFoundError when no BattleRecords entities are found.
func (brq *BattleRecordsQuery) Only(ctx context.Context) (*BattleRecords, error) {
	nodes, err := brq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{battlerecords.Label}
	default:
		return nil, &NotSingularError{battlerecords.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (brq *BattleRecordsQuery) OnlyX(ctx context.Context) *BattleRecords {
	node, err := brq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BattleRecords ID in the query.
// Returns a *NotSingularError when exactly one BattleRecords ID is not found.
// Returns a *NotFoundError when no entities are found.
func (brq *BattleRecordsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = brq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = &NotSingularError{battlerecords.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (brq *BattleRecordsQuery) OnlyIDX(ctx context.Context) int {
	id, err := brq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BattleRecordsSlice.
func (brq *BattleRecordsQuery) All(ctx context.Context) ([]*BattleRecords, error) {
	if err := brq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return brq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (brq *BattleRecordsQuery) AllX(ctx context.Context) []*BattleRecords {
	nodes, err := brq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BattleRecords IDs.
func (brq *BattleRecordsQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := brq.Select(battlerecords.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (brq *BattleRecordsQuery) IDsX(ctx context.Context) []int {
	ids, err := brq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (brq *BattleRecordsQuery) Count(ctx context.Context) (int, error) {
	if err := brq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return brq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (brq *BattleRecordsQuery) CountX(ctx context.Context) int {
	count, err := brq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (brq *BattleRecordsQuery) Exist(ctx context.Context) (bool, error) {
	if err := brq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return brq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (brq *BattleRecordsQuery) ExistX(ctx context.Context) bool {
	exist, err := brq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BattleRecordsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (brq *BattleRecordsQuery) Clone() *BattleRecordsQuery {
	if brq == nil {
		return nil
	}
	return &BattleRecordsQuery{
		config:            brq.config,
		limit:             brq.limit,
		offset:            brq.offset,
		order:             append([]OrderFunc{}, brq.order...),
		predicates:        append([]predicate.BattleRecords{}, brq.predicates...),
		withUseParty:      brq.withUseParty.Clone(),
		withOpponentParty: brq.withOpponentParty.Clone(),
		// clone intermediate query.
		sql:  brq.sql.Clone(),
		path: brq.path,
	}
}

// WithUseParty tells the query-builder to eager-load the nodes that are connected to
// the "use_party" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BattleRecordsQuery) WithUseParty(opts ...func(*PartyQuery)) *BattleRecordsQuery {
	query := &PartyQuery{config: brq.config}
	for _, opt := range opts {
		opt(query)
	}
	brq.withUseParty = query
	return brq
}

// WithOpponentParty tells the query-builder to eager-load the nodes that are connected to
// the "opponent_party" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BattleRecordsQuery) WithOpponentParty(opts ...func(*BattleOpponentPartyQuery)) *BattleRecordsQuery {
	query := &BattleOpponentPartyQuery{config: brq.config}
	for _, opt := range opts {
		opt(query)
	}
	brq.withOpponentParty = query
	return brq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PartyID int `json:"party_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BattleRecords.Query().
//		GroupBy(battlerecords.FieldPartyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (brq *BattleRecordsQuery) GroupBy(field string, fields ...string) *BattleRecordsGroupBy {
	group := &BattleRecordsGroupBy{config: brq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return brq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PartyID int `json:"party_id,omitempty"`
//	}
//
//	client.BattleRecords.Query().
//		Select(battlerecords.FieldPartyID).
//		Scan(ctx, &v)
//
func (brq *BattleRecordsQuery) Select(fields ...string) *BattleRecordsSelect {
	brq.fields = append(brq.fields, fields...)
	return &BattleRecordsSelect{BattleRecordsQuery: brq}
}

func (brq *BattleRecordsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range brq.fields {
		if !battlerecords.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if brq.path != nil {
		prev, err := brq.path(ctx)
		if err != nil {
			return err
		}
		brq.sql = prev
	}
	return nil
}

func (brq *BattleRecordsQuery) sqlAll(ctx context.Context) ([]*BattleRecords, error) {
	var (
		nodes       = []*BattleRecords{}
		_spec       = brq.querySpec()
		loadedTypes = [2]bool{
			brq.withUseParty != nil,
			brq.withOpponentParty != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &BattleRecords{config: brq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, brq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := brq.withUseParty; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*BattleRecords)
		for i := range nodes {
			fk := nodes[i].PartyID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(party.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "party_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.UseParty = n
			}
		}
	}

	if query := brq.withOpponentParty; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*BattleRecords)
		for i := range nodes {
			fk := nodes[i].BattleOpponentPartyID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(battleopponentparty.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "battle_opponent_party_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.OpponentParty = n
			}
		}
	}

	return nodes, nil
}

func (brq *BattleRecordsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := brq.querySpec()
	return sqlgraph.CountNodes(ctx, brq.driver, _spec)
}

func (brq *BattleRecordsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := brq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (brq *BattleRecordsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   battlerecords.Table,
			Columns: battlerecords.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: battlerecords.FieldID,
			},
		},
		From:   brq.sql,
		Unique: true,
	}
	if unique := brq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := brq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, battlerecords.FieldID)
		for i := range fields {
			if fields[i] != battlerecords.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := brq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := brq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := brq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := brq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (brq *BattleRecordsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(brq.driver.Dialect())
	t1 := builder.Table(battlerecords.Table)
	columns := brq.fields
	if len(columns) == 0 {
		columns = battlerecords.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if brq.sql != nil {
		selector = brq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range brq.predicates {
		p(selector)
	}
	for _, p := range brq.order {
		p(selector)
	}
	if offset := brq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := brq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BattleRecordsGroupBy is the group-by builder for BattleRecords entities.
type BattleRecordsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (brgb *BattleRecordsGroupBy) Aggregate(fns ...AggregateFunc) *BattleRecordsGroupBy {
	brgb.fns = append(brgb.fns, fns...)
	return brgb
}

// Scan applies the group-by query and scans the result into the given value.
func (brgb *BattleRecordsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := brgb.path(ctx)
	if err != nil {
		return err
	}
	brgb.sql = query
	return brgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := brgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(brgb.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := brgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) StringsX(ctx context.Context) []string {
	v, err := brgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = brgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) StringX(ctx context.Context) string {
	v, err := brgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(brgb.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := brgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) IntsX(ctx context.Context) []int {
	v, err := brgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = brgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) IntX(ctx context.Context) int {
	v, err := brgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(brgb.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := brgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := brgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = brgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := brgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(brgb.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := brgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := brgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (brgb *BattleRecordsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = brgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (brgb *BattleRecordsGroupBy) BoolX(ctx context.Context) bool {
	v, err := brgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (brgb *BattleRecordsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range brgb.fields {
		if !battlerecords.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := brgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (brgb *BattleRecordsGroupBy) sqlQuery() *sql.Selector {
	selector := brgb.sql.Select()
	aggregation := make([]string, 0, len(brgb.fns))
	for _, fn := range brgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(brgb.fields)+len(brgb.fns))
		for _, f := range brgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(brgb.fields...)...)
}

// BattleRecordsSelect is the builder for selecting fields of BattleRecords entities.
type BattleRecordsSelect struct {
	*BattleRecordsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (brs *BattleRecordsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := brs.prepareQuery(ctx); err != nil {
		return err
	}
	brs.sql = brs.BattleRecordsQuery.sqlQuery(ctx)
	return brs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (brs *BattleRecordsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := brs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(brs.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := brs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (brs *BattleRecordsSelect) StringsX(ctx context.Context) []string {
	v, err := brs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = brs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (brs *BattleRecordsSelect) StringX(ctx context.Context) string {
	v, err := brs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(brs.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := brs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (brs *BattleRecordsSelect) IntsX(ctx context.Context) []int {
	v, err := brs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = brs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (brs *BattleRecordsSelect) IntX(ctx context.Context) int {
	v, err := brs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(brs.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := brs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (brs *BattleRecordsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := brs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = brs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (brs *BattleRecordsSelect) Float64X(ctx context.Context) float64 {
	v, err := brs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(brs.fields) > 1 {
		return nil, errors.New("ent: BattleRecordsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := brs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (brs *BattleRecordsSelect) BoolsX(ctx context.Context) []bool {
	v, err := brs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (brs *BattleRecordsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = brs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{battlerecords.Label}
	default:
		err = fmt.Errorf("ent: BattleRecordsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (brs *BattleRecordsSelect) BoolX(ctx context.Context) bool {
	v, err := brs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (brs *BattleRecordsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := brs.sql.Query()
	if err := brs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
