// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/forms"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/pokemons"
)

// FormsCreate is the builder for creating a Forms entity.
type FormsCreate struct {
	config
	mutation *FormsMutation
	hooks    []Hook
}

// SetFormName sets the "form_name" field.
func (fc *FormsCreate) SetFormName(s string) *FormsCreate {
	fc.mutation.SetFormName(s)
	return fc
}

// SetIsRegionalVariant sets the "is_regional_variant" field.
func (fc *FormsCreate) SetIsRegionalVariant(b bool) *FormsCreate {
	fc.mutation.SetIsRegionalVariant(b)
	return fc
}

// SetNillableIsRegionalVariant sets the "is_regional_variant" field if the given value is not nil.
func (fc *FormsCreate) SetNillableIsRegionalVariant(b *bool) *FormsCreate {
	if b != nil {
		fc.SetIsRegionalVariant(*b)
	}
	return fc
}

// SetRegionName sets the "regionName" field.
func (fc *FormsCreate) SetRegionName(s string) *FormsCreate {
	fc.mutation.SetRegionName(s)
	return fc
}

// AddFormHolderIDs adds the "form_holder" edge to the Pokemons entity by IDs.
func (fc *FormsCreate) AddFormHolderIDs(ids ...int) *FormsCreate {
	fc.mutation.AddFormHolderIDs(ids...)
	return fc
}

// AddFormHolder adds the "form_holder" edges to the Pokemons entity.
func (fc *FormsCreate) AddFormHolder(p ...*Pokemons) *FormsCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return fc.AddFormHolderIDs(ids...)
}

// Mutation returns the FormsMutation object of the builder.
func (fc *FormsCreate) Mutation() *FormsMutation {
	return fc.mutation
}

// Save creates the Forms in the database.
func (fc *FormsCreate) Save(ctx context.Context) (*Forms, error) {
	var (
		err  error
		node *Forms
	)
	fc.defaults()
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FormsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			if node, err = fc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			if fc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FormsCreate) SaveX(ctx context.Context) *Forms {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FormsCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FormsCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FormsCreate) defaults() {
	if _, ok := fc.mutation.IsRegionalVariant(); !ok {
		v := forms.DefaultIsRegionalVariant
		fc.mutation.SetIsRegionalVariant(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FormsCreate) check() error {
	if _, ok := fc.mutation.FormName(); !ok {
		return &ValidationError{Name: "form_name", err: errors.New(`ent: missing required field "form_name"`)}
	}
	if v, ok := fc.mutation.FormName(); ok {
		if err := forms.FormNameValidator(v); err != nil {
			return &ValidationError{Name: "form_name", err: fmt.Errorf(`ent: validator failed for field "form_name": %w`, err)}
		}
	}
	if _, ok := fc.mutation.IsRegionalVariant(); !ok {
		return &ValidationError{Name: "is_regional_variant", err: errors.New(`ent: missing required field "is_regional_variant"`)}
	}
	if _, ok := fc.mutation.RegionName(); !ok {
		return &ValidationError{Name: "regionName", err: errors.New(`ent: missing required field "regionName"`)}
	}
	if v, ok := fc.mutation.RegionName(); ok {
		if err := forms.RegionNameValidator(v); err != nil {
			return &ValidationError{Name: "regionName", err: fmt.Errorf(`ent: validator failed for field "regionName": %w`, err)}
		}
	}
	return nil
}

func (fc *FormsCreate) sqlSave(ctx context.Context) (*Forms, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fc *FormsCreate) createSpec() (*Forms, *sqlgraph.CreateSpec) {
	var (
		_node = &Forms{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: forms.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: forms.FieldID,
			},
		}
	)
	if value, ok := fc.mutation.FormName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: forms.FieldFormName,
		})
		_node.FormName = value
	}
	if value, ok := fc.mutation.IsRegionalVariant(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: forms.FieldIsRegionalVariant,
		})
		_node.IsRegionalVariant = value
	}
	if value, ok := fc.mutation.RegionName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: forms.FieldRegionName,
		})
		_node.RegionName = value
	}
	if nodes := fc.mutation.FormHolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   forms.FormHolderTable,
			Columns: []string{forms.FormHolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemons.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FormsCreateBulk is the builder for creating many Forms entities in bulk.
type FormsCreateBulk struct {
	config
	builders []*FormsCreate
}

// Save creates the Forms entities in the database.
func (fcb *FormsCreateBulk) Save(ctx context.Context) ([]*Forms, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Forms, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FormsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FormsCreateBulk) SaveX(ctx context.Context) []*Forms {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FormsCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FormsCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
