// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/helditems"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/predicate"
)

// HeldItemsDelete is the builder for deleting a HeldItems entity.
type HeldItemsDelete struct {
	config
	hooks    []Hook
	mutation *HeldItemsMutation
}

// Where appends a list predicates to the HeldItemsDelete builder.
func (hid *HeldItemsDelete) Where(ps ...predicate.HeldItems) *HeldItemsDelete {
	hid.mutation.Where(ps...)
	return hid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hid *HeldItemsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(hid.hooks) == 0 {
		affected, err = hid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeldItemsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hid.mutation = mutation
			affected, err = hid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(hid.hooks) - 1; i >= 0; i-- {
			if hid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (hid *HeldItemsDelete) ExecX(ctx context.Context) int {
	n, err := hid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hid *HeldItemsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: helditems.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: helditems.FieldID,
			},
		},
	}
	if ps := hid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, hid.driver, _spec)
}

// HeldItemsDeleteOne is the builder for deleting a single HeldItems entity.
type HeldItemsDeleteOne struct {
	hid *HeldItemsDelete
}

// Exec executes the deletion query.
func (hido *HeldItemsDeleteOne) Exec(ctx context.Context) error {
	n, err := hido.hid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{helditems.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hido *HeldItemsDeleteOne) ExecX(ctx context.Context) {
	hido.hid.ExecX(ctx)
}
