// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/helditems"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/trainedpokemondetails"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/property"
)

// HeldItemsCreate is the builder for creating a HeldItems entity.
type HeldItemsCreate struct {
	config
	mutation *HeldItemsMutation
	hooks    []Hook
}

// SetPhysicalMovePowerCorrectionValue sets the "physical_move_power_correction_value" field.
func (hic *HeldItemsCreate) SetPhysicalMovePowerCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetPhysicalMovePowerCorrectionValue(i)
	return hic
}

// SetNillablePhysicalMovePowerCorrectionValue sets the "physical_move_power_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillablePhysicalMovePowerCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetPhysicalMovePowerCorrectionValue(*i)
	}
	return hic
}

// SetSpecialMovePowerCorrectionValue sets the "special_move_power_correction_value" field.
func (hic *HeldItemsCreate) SetSpecialMovePowerCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetSpecialMovePowerCorrectionValue(i)
	return hic
}

// SetNillableSpecialMovePowerCorrectionValue sets the "special_move_power_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableSpecialMovePowerCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetSpecialMovePowerCorrectionValue(*i)
	}
	return hic
}

// SetAttackPowerCorrectionValue sets the "attack_power_correction_value" field.
func (hic *HeldItemsCreate) SetAttackPowerCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetAttackPowerCorrectionValue(i)
	return hic
}

// SetNillableAttackPowerCorrectionValue sets the "attack_power_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableAttackPowerCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetAttackPowerCorrectionValue(*i)
	}
	return hic
}

// SetSpecialAttackPowerCorrectionValue sets the "special_attack_power_correction_value" field.
func (hic *HeldItemsCreate) SetSpecialAttackPowerCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetSpecialAttackPowerCorrectionValue(i)
	return hic
}

// SetNillableSpecialAttackPowerCorrectionValue sets the "special_attack_power_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableSpecialAttackPowerCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetSpecialAttackPowerCorrectionValue(*i)
	}
	return hic
}

// SetAttackCorrectionValue sets the "attack_correction_value" field.
func (hic *HeldItemsCreate) SetAttackCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetAttackCorrectionValue(i)
	return hic
}

// SetNillableAttackCorrectionValue sets the "attack_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableAttackCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetAttackCorrectionValue(*i)
	}
	return hic
}

// SetSpecialAttackCorrectionValue sets the "special_attack_correction_value" field.
func (hic *HeldItemsCreate) SetSpecialAttackCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetSpecialAttackCorrectionValue(i)
	return hic
}

// SetNillableSpecialAttackCorrectionValue sets the "special_attack_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableSpecialAttackCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetSpecialAttackCorrectionValue(*i)
	}
	return hic
}

// SetDeffenseCorrectionValue sets the "deffense_correction_value" field.
func (hic *HeldItemsCreate) SetDeffenseCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetDeffenseCorrectionValue(i)
	return hic
}

// SetNillableDeffenseCorrectionValue sets the "deffense_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableDeffenseCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetDeffenseCorrectionValue(*i)
	}
	return hic
}

// SetSpecialDeffenseCorrectionValue sets the "special_deffense_correction_value" field.
func (hic *HeldItemsCreate) SetSpecialDeffenseCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetSpecialDeffenseCorrectionValue(i)
	return hic
}

// SetNillableSpecialDeffenseCorrectionValue sets the "special_deffense_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableSpecialDeffenseCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetSpecialDeffenseCorrectionValue(*i)
	}
	return hic
}

// SetDamageCorrectionType1 sets the "damage_correction_type1" field.
func (hic *HeldItemsCreate) SetDamageCorrectionType1(pr property.Types) *HeldItemsCreate {
	hic.mutation.SetDamageCorrectionType1(pr)
	return hic
}

// SetDamageCorrectionValue1 sets the "damage_correction_value1" field.
func (hic *HeldItemsCreate) SetDamageCorrectionValue1(i int) *HeldItemsCreate {
	hic.mutation.SetDamageCorrectionValue1(i)
	return hic
}

// SetNillableDamageCorrectionValue1 sets the "damage_correction_value1" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableDamageCorrectionValue1(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetDamageCorrectionValue1(*i)
	}
	return hic
}

// SetDamageCorrectionType2 sets the "damage_correction_type2" field.
func (hic *HeldItemsCreate) SetDamageCorrectionType2(pr property.Types) *HeldItemsCreate {
	hic.mutation.SetDamageCorrectionType2(pr)
	return hic
}

// SetNillableDamageCorrectionType2 sets the "damage_correction_type2" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableDamageCorrectionType2(pr *property.Types) *HeldItemsCreate {
	if pr != nil {
		hic.SetDamageCorrectionType2(*pr)
	}
	return hic
}

// SetDamageCorrectionValue2 sets the "damage_correction_value2" field.
func (hic *HeldItemsCreate) SetDamageCorrectionValue2(i int) *HeldItemsCreate {
	hic.mutation.SetDamageCorrectionValue2(i)
	return hic
}

// SetNillableDamageCorrectionValue2 sets the "damage_correction_value2" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableDamageCorrectionValue2(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetDamageCorrectionValue2(*i)
	}
	return hic
}

// SetWeightCorrectionValue sets the "weight_correction_value" field.
func (hic *HeldItemsCreate) SetWeightCorrectionValue(i int) *HeldItemsCreate {
	hic.mutation.SetWeightCorrectionValue(i)
	return hic
}

// SetNillableWeightCorrectionValue sets the "weight_correction_value" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableWeightCorrectionValue(i *int) *HeldItemsCreate {
	if i != nil {
		hic.SetWeightCorrectionValue(*i)
	}
	return hic
}

// SetName sets the "name" field.
func (hic *HeldItemsCreate) SetName(s string) *HeldItemsCreate {
	hic.mutation.SetName(s)
	return hic
}

// SetDescription sets the "description" field.
func (hic *HeldItemsCreate) SetDescription(s string) *HeldItemsCreate {
	hic.mutation.SetDescription(s)
	return hic
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (hic *HeldItemsCreate) SetNillableDescription(s *string) *HeldItemsCreate {
	if s != nil {
		hic.SetDescription(*s)
	}
	return hic
}

// AddToTrainedPokemonItemIDs adds the "to_trained_pokemon_item" edge to the TrainedPokemonDetails entity by IDs.
func (hic *HeldItemsCreate) AddToTrainedPokemonItemIDs(ids ...int) *HeldItemsCreate {
	hic.mutation.AddToTrainedPokemonItemIDs(ids...)
	return hic
}

// AddToTrainedPokemonItem adds the "to_trained_pokemon_item" edges to the TrainedPokemonDetails entity.
func (hic *HeldItemsCreate) AddToTrainedPokemonItem(t ...*TrainedPokemonDetails) *HeldItemsCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return hic.AddToTrainedPokemonItemIDs(ids...)
}

// Mutation returns the HeldItemsMutation object of the builder.
func (hic *HeldItemsCreate) Mutation() *HeldItemsMutation {
	return hic.mutation
}

// Save creates the HeldItems in the database.
func (hic *HeldItemsCreate) Save(ctx context.Context) (*HeldItems, error) {
	var (
		err  error
		node *HeldItems
	)
	hic.defaults()
	if len(hic.hooks) == 0 {
		if err = hic.check(); err != nil {
			return nil, err
		}
		node, err = hic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HeldItemsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hic.check(); err != nil {
				return nil, err
			}
			hic.mutation = mutation
			if node, err = hic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hic.hooks) - 1; i >= 0; i-- {
			if hic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hic *HeldItemsCreate) SaveX(ctx context.Context) *HeldItems {
	v, err := hic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hic *HeldItemsCreate) Exec(ctx context.Context) error {
	_, err := hic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hic *HeldItemsCreate) ExecX(ctx context.Context) {
	if err := hic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hic *HeldItemsCreate) defaults() {
	if _, ok := hic.mutation.PhysicalMovePowerCorrectionValue(); !ok {
		v := helditems.DefaultPhysicalMovePowerCorrectionValue
		hic.mutation.SetPhysicalMovePowerCorrectionValue(v)
	}
	if _, ok := hic.mutation.SpecialMovePowerCorrectionValue(); !ok {
		v := helditems.DefaultSpecialMovePowerCorrectionValue
		hic.mutation.SetSpecialMovePowerCorrectionValue(v)
	}
	if _, ok := hic.mutation.AttackPowerCorrectionValue(); !ok {
		v := helditems.DefaultAttackPowerCorrectionValue
		hic.mutation.SetAttackPowerCorrectionValue(v)
	}
	if _, ok := hic.mutation.SpecialAttackPowerCorrectionValue(); !ok {
		v := helditems.DefaultSpecialAttackPowerCorrectionValue
		hic.mutation.SetSpecialAttackPowerCorrectionValue(v)
	}
	if _, ok := hic.mutation.AttackCorrectionValue(); !ok {
		v := helditems.DefaultAttackCorrectionValue
		hic.mutation.SetAttackCorrectionValue(v)
	}
	if _, ok := hic.mutation.SpecialAttackCorrectionValue(); !ok {
		v := helditems.DefaultSpecialAttackCorrectionValue
		hic.mutation.SetSpecialAttackCorrectionValue(v)
	}
	if _, ok := hic.mutation.DeffenseCorrectionValue(); !ok {
		v := helditems.DefaultDeffenseCorrectionValue
		hic.mutation.SetDeffenseCorrectionValue(v)
	}
	if _, ok := hic.mutation.SpecialDeffenseCorrectionValue(); !ok {
		v := helditems.DefaultSpecialDeffenseCorrectionValue
		hic.mutation.SetSpecialDeffenseCorrectionValue(v)
	}
	if _, ok := hic.mutation.DamageCorrectionValue1(); !ok {
		v := helditems.DefaultDamageCorrectionValue1
		hic.mutation.SetDamageCorrectionValue1(v)
	}
	if _, ok := hic.mutation.WeightCorrectionValue(); !ok {
		v := helditems.DefaultWeightCorrectionValue
		hic.mutation.SetWeightCorrectionValue(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hic *HeldItemsCreate) check() error {
	if _, ok := hic.mutation.PhysicalMovePowerCorrectionValue(); !ok {
		return &ValidationError{Name: "physical_move_power_correction_value", err: errors.New(`ent: missing required field "physical_move_power_correction_value"`)}
	}
	if _, ok := hic.mutation.SpecialMovePowerCorrectionValue(); !ok {
		return &ValidationError{Name: "special_move_power_correction_value", err: errors.New(`ent: missing required field "special_move_power_correction_value"`)}
	}
	if _, ok := hic.mutation.AttackPowerCorrectionValue(); !ok {
		return &ValidationError{Name: "attack_power_correction_value", err: errors.New(`ent: missing required field "attack_power_correction_value"`)}
	}
	if _, ok := hic.mutation.SpecialAttackPowerCorrectionValue(); !ok {
		return &ValidationError{Name: "special_attack_power_correction_value", err: errors.New(`ent: missing required field "special_attack_power_correction_value"`)}
	}
	if _, ok := hic.mutation.AttackCorrectionValue(); !ok {
		return &ValidationError{Name: "attack_correction_value", err: errors.New(`ent: missing required field "attack_correction_value"`)}
	}
	if _, ok := hic.mutation.SpecialAttackCorrectionValue(); !ok {
		return &ValidationError{Name: "special_attack_correction_value", err: errors.New(`ent: missing required field "special_attack_correction_value"`)}
	}
	if _, ok := hic.mutation.DeffenseCorrectionValue(); !ok {
		return &ValidationError{Name: "deffense_correction_value", err: errors.New(`ent: missing required field "deffense_correction_value"`)}
	}
	if _, ok := hic.mutation.SpecialDeffenseCorrectionValue(); !ok {
		return &ValidationError{Name: "special_deffense_correction_value", err: errors.New(`ent: missing required field "special_deffense_correction_value"`)}
	}
	if _, ok := hic.mutation.DamageCorrectionType1(); !ok {
		return &ValidationError{Name: "damage_correction_type1", err: errors.New(`ent: missing required field "damage_correction_type1"`)}
	}
	if v, ok := hic.mutation.DamageCorrectionType1(); ok {
		if err := helditems.DamageCorrectionType1Validator(string(v)); err != nil {
			return &ValidationError{Name: "damage_correction_type1", err: fmt.Errorf(`ent: validator failed for field "damage_correction_type1": %w`, err)}
		}
	}
	if _, ok := hic.mutation.DamageCorrectionValue1(); !ok {
		return &ValidationError{Name: "damage_correction_value1", err: errors.New(`ent: missing required field "damage_correction_value1"`)}
	}
	if _, ok := hic.mutation.WeightCorrectionValue(); !ok {
		return &ValidationError{Name: "weight_correction_value", err: errors.New(`ent: missing required field "weight_correction_value"`)}
	}
	if _, ok := hic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if v, ok := hic.mutation.Name(); ok {
		if err := helditems.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "name": %w`, err)}
		}
	}
	return nil
}

func (hic *HeldItemsCreate) sqlSave(ctx context.Context) (*HeldItems, error) {
	_node, _spec := hic.createSpec()
	if err := sqlgraph.CreateNode(ctx, hic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hic *HeldItemsCreate) createSpec() (*HeldItems, *sqlgraph.CreateSpec) {
	var (
		_node = &HeldItems{config: hic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: helditems.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: helditems.FieldID,
			},
		}
	)
	if value, ok := hic.mutation.PhysicalMovePowerCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldPhysicalMovePowerCorrectionValue,
		})
		_node.PhysicalMovePowerCorrectionValue = value
	}
	if value, ok := hic.mutation.SpecialMovePowerCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldSpecialMovePowerCorrectionValue,
		})
		_node.SpecialMovePowerCorrectionValue = value
	}
	if value, ok := hic.mutation.AttackPowerCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldAttackPowerCorrectionValue,
		})
		_node.AttackPowerCorrectionValue = value
	}
	if value, ok := hic.mutation.SpecialAttackPowerCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldSpecialAttackPowerCorrectionValue,
		})
		_node.SpecialAttackPowerCorrectionValue = value
	}
	if value, ok := hic.mutation.AttackCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldAttackCorrectionValue,
		})
		_node.AttackCorrectionValue = value
	}
	if value, ok := hic.mutation.SpecialAttackCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldSpecialAttackCorrectionValue,
		})
		_node.SpecialAttackCorrectionValue = value
	}
	if value, ok := hic.mutation.DeffenseCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldDeffenseCorrectionValue,
		})
		_node.DeffenseCorrectionValue = value
	}
	if value, ok := hic.mutation.SpecialDeffenseCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldSpecialDeffenseCorrectionValue,
		})
		_node.SpecialDeffenseCorrectionValue = value
	}
	if value, ok := hic.mutation.DamageCorrectionType1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: helditems.FieldDamageCorrectionType1,
		})
		_node.DamageCorrectionType1 = value
	}
	if value, ok := hic.mutation.DamageCorrectionValue1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldDamageCorrectionValue1,
		})
		_node.DamageCorrectionValue1 = value
	}
	if value, ok := hic.mutation.DamageCorrectionType2(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: helditems.FieldDamageCorrectionType2,
		})
		_node.DamageCorrectionType2 = value
	}
	if value, ok := hic.mutation.DamageCorrectionValue2(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldDamageCorrectionValue2,
		})
		_node.DamageCorrectionValue2 = value
	}
	if value, ok := hic.mutation.WeightCorrectionValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: helditems.FieldWeightCorrectionValue,
		})
		_node.WeightCorrectionValue = value
	}
	if value, ok := hic.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: helditems.FieldName,
		})
		_node.Name = value
	}
	if value, ok := hic.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: helditems.FieldDescription,
		})
		_node.Description = value
	}
	if nodes := hic.mutation.ToTrainedPokemonItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   helditems.ToTrainedPokemonItemTable,
			Columns: []string{helditems.ToTrainedPokemonItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: trainedpokemondetails.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HeldItemsCreateBulk is the builder for creating many HeldItems entities in bulk.
type HeldItemsCreateBulk struct {
	config
	builders []*HeldItemsCreate
}

// Save creates the HeldItems entities in the database.
func (hicb *HeldItemsCreateBulk) Save(ctx context.Context) ([]*HeldItems, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hicb.builders))
	nodes := make([]*HeldItems, len(hicb.builders))
	mutators := make([]Mutator, len(hicb.builders))
	for i := range hicb.builders {
		func(i int, root context.Context) {
			builder := hicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HeldItemsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hicb *HeldItemsCreateBulk) SaveX(ctx context.Context) []*HeldItems {
	v, err := hicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hicb *HeldItemsCreateBulk) Exec(ctx context.Context) error {
	_, err := hicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hicb *HeldItemsCreateBulk) ExecX(ctx context.Context) {
	if err := hicb.Exec(ctx); err != nil {
		panic(err)
	}
}
