// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/predicate"
	"github.com/Symthy/PokeRest/pokeRest/adapters/orm/autogen/ent/trainedpokemondetails"
)

// TrainedPokemonDetailsDelete is the builder for deleting a TrainedPokemonDetails entity.
type TrainedPokemonDetailsDelete struct {
	config
	hooks    []Hook
	mutation *TrainedPokemonDetailsMutation
}

// Where appends a list predicates to the TrainedPokemonDetailsDelete builder.
func (tpdd *TrainedPokemonDetailsDelete) Where(ps ...predicate.TrainedPokemonDetails) *TrainedPokemonDetailsDelete {
	tpdd.mutation.Where(ps...)
	return tpdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tpdd *TrainedPokemonDetailsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tpdd.hooks) == 0 {
		affected, err = tpdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TrainedPokemonDetailsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tpdd.mutation = mutation
			affected, err = tpdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tpdd.hooks) - 1; i >= 0; i-- {
			if tpdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tpdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tpdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpdd *TrainedPokemonDetailsDelete) ExecX(ctx context.Context) int {
	n, err := tpdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tpdd *TrainedPokemonDetailsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: trainedpokemondetails.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: trainedpokemondetails.FieldID,
			},
		},
	}
	if ps := tpdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tpdd.driver, _spec)
}

// TrainedPokemonDetailsDeleteOne is the builder for deleting a single TrainedPokemonDetails entity.
type TrainedPokemonDetailsDeleteOne struct {
	tpdd *TrainedPokemonDetailsDelete
}

// Exec executes the deletion query.
func (tpddo *TrainedPokemonDetailsDeleteOne) Exec(ctx context.Context) error {
	n, err := tpddo.tpdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trainedpokemondetails.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tpddo *TrainedPokemonDetailsDeleteOne) ExecX(ctx context.Context) {
	tpddo.tpdd.ExecX(ctx)
}
